//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reker.MusicHubTile.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reker.MusicHubTile.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Tile for Bing Vision 的本地化字符串。
        /// </summary>
        public static string AboutPageBtnBingVisionTile {
            get {
                return ResourceManager.GetString("AboutPageBtnBingVisionTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 reker - click to follow 的本地化字符串。
        /// </summary>
        public static string AboutPageBtnHomePage {
            get {
                return ResourceManager.GetString("AboutPageBtnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More Apps 的本地化字符串。
        /// </summary>
        public static string AboutPageBtnMore {
            get {
                return ResourceManager.GetString("AboutPageBtnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rate 的本地化字符串。
        /// </summary>
        public static string AboutPageBtnRate {
            get {
                return ResourceManager.GetString("AboutPageBtnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By: 的本地化字符串。
        /// </summary>
        public static string AboutPageBy {
            get {
                return ResourceManager.GetString("AboutPageBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks to: 的本地化字符串。
        /// </summary>
        public static string AboutPageThanks {
            get {
                return ResourceManager.GetString("AboutPageThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marcio Andrade 的本地化字符串。
        /// </summary>
        public static string AboutPageThanksMarcioAndrade {
            get {
                return ResourceManager.GetString("AboutPageThanksMarcioAndrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Martin Anderson 的本地化字符串。
        /// </summary>
        public static string AboutPageThanksMartinAnderson {
            get {
                return ResourceManager.GetString("AboutPageThanksMartinAnderson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 about 的本地化字符串。
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MUSIC HUB TILE 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Hub Tile 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy 的本地化字符串。
        /// </summary>
        public static string BuyPageBtnBuy {
            get {
                return ResourceManager.GetString("BuyPageBtnBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string BuyPageBtnDonate {
            get {
                return ResourceManager.GetString("BuyPageBtnDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can buy full version to unlock all functions. If you have already bought before, please tap buy button again, it will be free. 的本地化字符串。
        /// </summary>
        public static string BuyPageBuyDescription {
            get {
                return ResourceManager.GetString("BuyPageBuyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can make additional donations to support development, thank you. 的本地化字符串。
        /// </summary>
        public static string BuyPageDonateDescription {
            get {
                return ResourceManager.GetString("BuyPageDonateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 buy 的本地化字符串。
        /// </summary>
        public static string BuyPageTitle {
            get {
                return ResourceManager.GetString("BuyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 donate 的本地化字符串。
        /// </summary>
        public static string BuyPageTitleDonate {
            get {
                return ResourceManager.GetString("BuyPageTitleDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://twitter.com/rekerchen 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 about 的本地化字符串。
        /// </summary>
        public static string MainPageAbmAbout {
            get {
                return ResourceManager.GetString("MainPageAbmAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 buy full version 的本地化字符串。
        /// </summary>
        public static string MainPageAbmBuy {
            get {
                return ResourceManager.GetString("MainPageAbmBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 additional donation 的本地化字符串。
        /// </summary>
        public static string MainPageAbmDonate {
            get {
                return ResourceManager.GetString("MainPageAbmDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch Music Hub 的本地化字符串。
        /// </summary>
        public static string MainPageBtnOpenHub {
            get {
                return ResourceManager.GetString("MainPageBtnOpenHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch directly next time 的本地化字符串。
        /// </summary>
        public static string MainPageChkLaunchDirectly {
            get {
                return ResourceManager.GetString("MainPageChkLaunchDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the button below to pin a tile of Music Hub on the &apos;Start&apos; Screen. 的本地化字符串。
        /// </summary>
        public static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need Windows Phone 8.1 Update 1 (OS verison &gt;= 8.10.14141.167) 的本地化字符串。
        /// </summary>
        public static string MainPageTestDescription {
            get {
                return ResourceManager.GetString("MainPageTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always &apos;Live&apos; 的本地化字符串。
        /// </summary>
        public static string MainPageTglAlwayShowLiveTile {
            get {
                return ResourceManager.GetString("MainPageTglAlwayShowLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 live 的本地化字符串。
        /// </summary>
        public static string MainPageTitleLive {
            get {
                return ResourceManager.GetString("MainPageTitleLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 opacity 的本地化字符串。
        /// </summary>
        public static string MainPageTitleOpacity {
            get {
                return ResourceManager.GetString("MainPageTitleOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 transparent 的本地化字符串。
        /// </summary>
        public static string MainPageTitleTransparent {
            get {
                return ResourceManager.GetString("MainPageTitleTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to buy. 的本地化字符串。
        /// </summary>
        public static string MsgBuyFailed {
            get {
                return ResourceManager.GetString("MsgBuyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for your support. 的本地化字符串。
        /// </summary>
        public static string MsgBuySuccess {
            get {
                return ResourceManager.GetString("MsgBuySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need buy full version to unlock this function. 的本地化字符串。
        /// </summary>
        public static string MsgNeedBuy {
            get {
                return ResourceManager.GetString("MsgNeedBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pinned 的本地化字符串。
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en-US 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        public static string TileName {
            get {
                return ResourceManager.GetString("TileName", resourceCulture);
            }
        }
    }
}
